### ISSUE TITLE
PHP 7.2 throws ErrorException (E_DEPRECATED): __autoload() is deprecated, use spl_autoload_register() instead on line 99 of Autoload.php

### ISSUE THREAD

**Issue by eseyden** [apereo/phpCAS#255]
It looks like the backwards comparability fix is broken in the new version of PHP

**Comment by eseyden** [comment]
I noticed the master branch has a fix for this; is there a good way to get that into a release?

**Comment by jfritschi** [comment]
You can simply use the green download or clone button on GitHub. It's more or less a new package from master.

**Comment by eseyden** [comment]
Ideally I'd like to use packagist and composer to get a PHP 7.2 compatible version of phpCAS. I'm not comfortable following master while there is major development work on v2 of phpCAS

**Comment by eseyden** [comment]
Reading into your composer.json file it looks like I can target 1.3.x-dev and get the master branch.
Its a little better peace of mind than just targeting dev-master so I don't randomly get 2.0 when its released.  Thanks a bunch.

**Comment by jfritschi** [comment]
Yes, that is probably the best way.

**Comment by Nirzol** [comment]
Hello, which require I have to use for my composer ?
actualité I use this "jasig/phpcas": "1.3.*"

I have to change to "jasig/phpcas": "dev-master"  ? to get this fix ?

Thanks

**Comment by adampk90** [comment]
I just updated my composer.json to use "1.3.x-dev", but it still appears to pull "dev-master"... are we sure we won't get 2.0 when it's eventually pushed?

**Comment by diam** [comment]
Bonjour,

I had the same problem and solve it directly by **modifying the `CAS-1.3.5/CAS/Autoload.php` file**. The problem was that php7.2 cry because it think that `__autoload()` is defined although it is **never** defined (because of the never executed else branch of the `if then else` statement.

This `if then else` statement is only usefull if phpCAS-1.3.5 is supposed to be working under php5.0.x! 
Is it really true?

**My solution consisted simply in commenting (of suppressing) the `elseif` branch.**.  Then I renamed the `CAS-1.3.5/` directory with a personal suffix.

It works on php5.3.29, php7.2.0 and php7.2.2.

Regard,
-- Maurice

**Comment by eseyden** [comment]
@adampk90 I suppose we can just leave this issue open until there is a tagged version of 1.3 with this fix. I would assume the maintainers wouldn't burn us on this intentionally though. Use at your own discretion.

**Comment by jfritschi** [comment]
Has been release in new version. Closing issue
