### ISSUE TITLE
SLO not working

### ISSUE THREAD

**Issue by vaggelis2018** [apereo/phpCAS#287]
According to manual if i log out in cas a post request to a given url is coming to inform other services that i have logged out. The post request is coming on my debug window but after i refresh the page the user is still logged out. Any way to solve this issue. Cas version is 5.2

**Comment by jfritschi** [comment]
Please review the debug logs if a SLO request actually arrives. Many times the issue is that the logout request does not reach the cas applications. This can have many reasons (e.g. firewall, DNS, no certificate trust).

Often times it's a simple TLS issues or even the problem that no TLS is used at all on a service. This is a mandatory requirement since the authentication tokens are part of the logout message.

**Comment by vaggelis2018** [comment]
Hello and sorry for the late response. The request arrives as i mentioned. The problem is that in version 5.2 the NameID arrtribute of the saml request has a value of NOT_USED. This makes it impossible to validate for which user the request is. In versions 6 of cas this is not happening. Any way to make it work?

**Comment by jfritschi** [comment]
The SLO of phpcas relies purely on the session id being the service or proxy Ticket (ST/PT) or being directly derived from it. Since phpcas does not use any persistent storage (aside from special proxy use cases) there is no linkage to the user name. 
If you use any custom session logic you have to implement it in your own (through the hook functions we have)

The default logic is pretty simple:
- A phpcas session is created from a ST ticket by the cas server (php session id is derived from the ST value)
- Any user remains authenticated locally within the application through the php session
- If a SLO is triggered by the CAS server this includes the original ST. Through this ST we can calculate the actual php session id. For any valid request we simply terminate the associated php session is
