### ISSUE TITLE
phpCAS not sending logout request after session timeout

### ISSUE THREAD

**Issue by keithpotter21** [apereo/phpCAS#301]
If a user voluntarily clicks the logout link (and uses the phpCAS::logout() method, everything works fine. However, if the PHP session timeouts (after 24 mins), no logout request is sent to the iDP server. Is this something the library handles or does the app need to handle this? What is the proper way to handle this? I'm using phpCAS 1.3.4

Thanks in advance

**Comment by jfritschi** [comment]
Phpcas does not do this and this would also be a terrible feature.  This is also not the correct way to use the single log out. (It would also be very hard to implement since a session does not really time out actively. Simply the cookie/session lifetime expires. There is no easy way to run code on this event...)


You have to be careful with using the logout() feature and only do this if the user really knows what he is doing:

- A local (single application logout) is something a user can grasp
- Terminating all application sessions in your CAS federation is not very easy to grasp for the end user and has a high rate of error (how does the user know what "logout ..." exactly means and what applications are covered)
- Simply terminating all sessions has the chance of data loss of the user since you may simply terminate another application mid session with unsaved data
- Automatic termination of all sessions through the expiration of a single application session is even more problematic since the user is not even informed or actually triggers this actively
