### ISSUE TITLE
Deep Link, phpCAS and cross web browser authentication

### ISSUE THREAD

**Issue by Cyazd** [apereo/phpCAS#350]
Hi to everybody,

I have a web app and which displays a pdf book.
To connect to this webapp one has to authenticate via a CAS Server.
My app include phpCAS.

Here's the connection flow 

1) Connect to a webpage via a CAS server to access all the available books
2) Click on my book and be redirected to my webapp
3) Then communication between my webpage and the CAS Server to allow the connection.

Everything works well up to that point. 

I also have an Android app which only displays the webapp in a Webview environment. And when someone tries to access the webpage of my app, he will be ask if he wants to open it in the app.

The problem is that, as the app uses a different browser, it doesn't store cookies nor has the same user-agent, so that it asks for a re-authentication. So my question is : how do I avoid this reauthentication (transferring cookies for instance ?).

Thanking you in advance for your help.

**Comment by jfritschi** [comment]
The CAS SSO (central CAS server) session is maintained via cookie and only works inside a single browser. Not sure how one could transfer cookies between browsers... Neven tried that.
Since you are talking about mobile apps using the CAS proxy tickets is out of the question.

Just a wild idea: Probably the best idea would be to embed your own secret token (encrypted session id?) in the link to be accessed by the secondary app. Then your application will connect to your website and you can add some custom code to decode the token and "link" the two sessions.  (either same session ID? or just map to same account)

**Comment by phy25** [comment]
Agreeing with @jfritschi, I am afraid this is not something defined in CAS.

I have another idea of:

1. On the page that redirects users to the app, call `redirectToCas()` to get a new ticket from CAS and set `redirect_to` appropriately. Your user should already be authenticated on CAS server, so they won't see any login prompt.
2. On the page of `redirect_to` (can be the same as the one that "redirect users to the app"), don't call any phpCAS's `*Authentication()` method because that will consume the ticket. Instead, open the app with the query param containing the ticket.
3. In the app it might be on the same page. Your server should be able to check if the user comes from an app or is outside the app. Then you can go ahead to use `*Authentication()` to actually consume the ticket and log in.

As the user is not authenticated with CAS server in the app, if the session is lost or times out, users in the app still gets redirected to the CAS login page and will be asked for credentials. I am not aware of any web-based authentication protocol that addresses this, since it's really about sharing authentication server's login status **between devices** without user interaction, so it really relies on custom implementation on the authentication server.

I am going to close this issue but feel free to reopen if you have any further questions.
